const MESSAGES = {
    ID_INVALIDO_DEVE_SER_NUMERO: 'ID inválido. Deve ser um número.',
    FALHA_AO_LISTAR_CLIENTES: 'Falha ao listar clientes',
    FALHA_AO_BUSCAR_CLIENTE: 'Falha ao buscar cliente',
    CLIENTE_NAO_ENCONTRADO: 'Cliente não encontrado',
    PRODUTO_NAO_ENCONTRADO: 'Produto não encontrado',
    VENDA_NAO_ENCONTRADA: 'Venda não encontrada',
    CLIENTE_JA_EXISTE: 'Cliente já existe',
    PRODUTO_JA_EXISTE: 'Produto já existe',
    VENDA_JA_EXISTE: 'Venda já existe',
    PARAMETRO_NOME_E_OBRIGATORIO_PARA_A_BUSCA: 'Parâmetro "nome" é obrigatório para a busca.',
    NOME_DO_CLIENTE_E_OBRIGATORIO: 'O nome do cliente é obrigatório.',
    FALHA_AO_INSERIR_CLIENTE: 'Falha ao inserir o cliente.',
    CLIENTE_ATUALIZADO_COM_SUCESSO: 'Cliente atualizado com sucesso.',

    FALHA_AO_INSERIR_PRODUTO: 'Falha ao inserir o produto.',
    FALHA_AO_LISTAR_PRODUTOS: 'Falha ao listar produtos.',
    FALHA_AO_BUSCAR_PRODUTO: 'Falha ao buscar produto.',
    PRODUTO_ATUALIZADO_COM_SUCESSO: 'Produto atualizado com sucesso.',
    FALHA_AO_ATUALIZAR_PRODUTO: 'Falha ao atualizar o produto.',
    FALHA_AO_DELETAR_PRODUTO: 'Falha ao deletar o produto.',
    NOME_PRECO_E_ESTOQUE_SAO_OBRIGATORIOS: 'Nome, preço e estoque são obrigatórios.',
    NOME_DEVE_SER_UMA_STRING_NAO_VAZIA: 'Nome deve ser uma string não vazia.',
    PRECO_DEVE_SER_UM_NUMERO_MAIOR_QUE_ZERO: 'Preço deve ser um número maior que zero.',
    ESTOQUE_DEVE_SER_UM_NUMERO_INTEIRO_NAO_NEGATIVO: 'Estoque deve ser um número inteiro não negativo.',
    ESTOQUE_INSUFICIENTE_PARA_O_PRODUTO: 'Estoque insuficiente para o produto.',
    FALHA_AO_SUBTRAIR_ESTOQUE_DO_PRODUTO: 'Falha ao subtrair estoque do produto.',
    PRECO_UNITARIO_DEVE_SER_UM_NUMERO_MAIOR_QUE_ZERO: 'Preço unitário deve ser um número maior que zero.',
    CLIENTE_ID_PRODUTO_ID_QUANTIDADE_E_PRECO_UNITARIO_SAO_OBRIGATORIOS: 'Cliente ID, Produto ID, Quantidade e Preço Unitário são obrigatórios.',
    CLIENTE_ID_DEVE_SER_UM_NUMERO_INTEIRO_POSITIVO: 'Cliente ID deve ser um número inteiro positivo.',
    PRODUTO_ID_DEVE_SER_UM_NUMERO_INTEIRO_POSITIVO: 'Produto ID deve ser um número inteiro positivo.',
    QUANTIDADE_DEVE_SER_UM_NUMERO_INTEIRO_POSITIVO: 'Quantidade deve ser um número inteiro positivo.',
    FALHA_AO_INSERIR_VENDA: 'Falha ao inserir a venda.',
    FALHA_AO_LISTAR_VENDAS: 'Falha ao listar vendas.',
    FALHA_AO_BUSCAR_VENDA: 'Falha ao buscar a venda.',
    VENDA_ATUALIZADA_COM_SUCESSO: 'Venda atualizada com sucesso.',
    FALHA_AO_ATUALIZAR_VENDA: 'Falha ao atualizar a venda.',
    FALHA_AO_DELETAR_VENDA: 'Falha ao deletar a venda.',
    FALHA_AO_REGISTRAR_VENDA: 'Falha ao registrar a venda.',
    FALHA_AO_BUSCAR_VENDAS: 'Falha ao buscar vendas.',
    FALHA_AO_BUSCAR_VENDA_POR_ID: 'Falha ao buscar a venda por ID.',
    FALHA_AO_BUSCAR_VENDAS_POR_CLIENTE_ID: 'Falha ao buscar vendas por Cliente ID.',
    FALHA_AO_BUSCAR_TOTAL_DE_VENDAS_POR_PRODUTO: 'Falha ao buscar vendas totais do produto'
}

export default MESSAGES;